apiVersion: v1
kind: Pod
metadata:
  name: hostname-edge
  namespace: default
  labels:
    app: hostname-edge
spec:
  nodeName: edgenode1-1
  containers:
    - name: hostname
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          hostPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: hostname-svc
  namespace: edgemesh-test
spec:
  selector:
    app: hostname-edge
  ports:
    - name: http-0
      port: 12345
      protocol: TCP
      targetPort: 80
